root | DEBUG | 2020-11-21 10:35:04,873 | Number of records: 29
root | DEBUG | 2020-11-21 10:35:04,879 | Number of records: 37
root | ERROR | 2020-11-21 10:35:04,884 | Exception occurred due to wrong file path
Traceback (most recent call last):
  File "/Users/nusrat/PycharmProjects/census_analyser_project/main/census_analyser.py", line 25, in load_census_data
    with open(csv_file_path , 'r') as census_data:
FileNotFoundError: [Errno 2] No such file or directory: 'Users/nusrat/PycharmProjects/PythonProjects/census_analyser_project/main/IndiaStateCensusData.csv'
root | ERROR | 2020-11-21 10:35:04,894 | Exception occurred due to wrong file path
Traceback (most recent call last):
  File "/Users/nusrat/PycharmProjects/census_analyser_project/main/census_analyser.py", line 25, in load_census_data
    with open(csv_file_path , 'r') as census_data:
FileNotFoundError: [Errno 2] No such file or directory: 'Users/nusrat/PycharmProjects/PythonProjects/census_analyser_project/main/IndiaStateCode.csv'
root | ERROR | 2020-11-21 10:35:04,900 | Exception occurred due to wrong file extension
NoneType: None
root | ERROR | 2020-11-21 10:35:04,907 | Exception occurred due to wrong file extension
NoneType: None
